export const BIO_CREDIT_HOURS: Record<string, number> = {
  "mathematics 0": 0,
  "biology 0": 0,
  "computer fundamentals it": 2,
  "introduction to biophysics": 3,
  "creative thinking": 3,
  "english for science technology": 3,
  "structured programming": 2,
  "mathematics 1": 3,
  "biomedical information systems": 2,
  "introduction to biochemistry": 2,
  "linear algebra": 3,
  genomics: 2,
  "object oriented programming": 2,
  "probability and biostatistics": 2,
  electronics: 2,
  "human rights and anti corruption": 3,
  "medical signal informatics": 2,
  "introduction to molecular cell biology": 2,
  "introduction to computational biology bioinformatics": 3,
  "computer networks": 3,
  "programming with python": 3,
  "introduction to algorithms data structures": 2,
  "logic design": 3,
  "numerical analysis": 2,
  "human diseases": 2,
  "computer security": 2,
  "introduction to machine learning": 3,
  "biological data mining": 2,
  "differential and integral calculus": 3,
  "computer vision and robotics": 3,
  databases: 3,
  "cloud computing": 2,
  "web development": 2,
  "discrete mathematics": 2,
  "deep learning in healthcare": 3,
  "human computer interaction": 2,
  "digital signal processing": 3,
  "genetic algorithm": 3,
  "natural language processing": 2,
  biometrics: 3,
  "fundamentals of computer graphics": 2,
  "computational intelligence": 2,
  "dna sequence analysis": 2,
  "big biological data": 3,
  "internet of things in healthcare": 3,
  "software testing": 3,
  "marketing and communication skills": 3,
  "ai for leaders": 2,
  "medical information visualization": 2,
  "health information management": 2,
  "ai in forensic analysis": 3,
  "industrial biomedical systems": 3,
  "software development for mobile apps": 3,
  "practical project": 3,
  "computer aided drugs design": 3,
  "bioinformatics for cancer genomics": 3,
  "cognitive interaction": 3,
  "computational genomics": 3,
  "applications of biotechnology": 2,
  "nanotechnology and artificial intelligence": 2,
  "advanced topics in computational biology bioinformatics": 3,
  "biomedical data acquisition": 3,
  "multi agent system design": 3,
};
